"""Utilities for mapping source database types to IBM DB2 types."""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Callable, Dict, List, Optional, Tuple


@dataclass
class TypeMappingResult:
    """Result of a type mapping operation."""

    target_type: str
    warning: Optional[str] = None


def _parse_type_parameters(parameters: Optional[str]) -> List[str]:
    if not parameters:
        return []
    parts: List[str] = []
    current: List[str] = []
    depth = 0
    for char in parameters:
        if char == "(":
            depth += 1
            current.append(char)
        elif char == ")":
            depth = max(0, depth - 1)
            current.append(char)
        elif char == "," and depth == 0:
            part = "".join(current).strip()
            parts.append(part)
            current = []
        else:
            current.append(char)
    if current:
        parts.append("".join(current).strip())
    return parts


def _normalize_identifier(identifier: str) -> str:
    identifier = identifier.strip().upper()
    if identifier.startswith("[") and identifier.endswith("]"):
        return identifier[1:-1]
    if identifier.startswith("\"") and identifier.endswith("\""):
        return identifier[1:-1]
    if identifier.startswith("`") and identifier.endswith("`"):
        return identifier[1:-1]
    return identifier


def _with_optional_length(target: str, params: List[str]) -> str:
    if not params:
        return target
    if params[0].upper() == "MAX":
        return "CLOB"
    return f"{target}({params[0]})"


def _with_precision_scale(target: str, params: List[str]) -> str:
    if not params:
        return target
    if len(params) == 1:
        return f"{target}({params[0]})"
    return f"{target}({params[0]}, {params[1]})"


def _handle_number(params: List[str]) -> str:
    if not params:
        return "DECIMAL(31, 0)"
    if len(params) == 1:
        return f"DECIMAL({params[0]}, 0)"
    return f"DECIMAL({params[0]}, {params[1]})"


def _handle_float(params: List[str]) -> str:
    if params and params[0] == "53":
        return "DOUBLE"
    return "REAL"


def _handle_raw(params: List[str]) -> str:
    if not params:
        return "BLOB"
    return f"BLOB({params[0]})"


def _identity_warning(original: str) -> str:
    return (
        "IDENTITY/GUID columns require manual migration to DB2 sequences or GENERATED BY DEFAULT definitions. "
        f"Found: {original}"
    )


class TypeMapper:
    """Map source database column types to DB2 column types."""

    def __init__(self, source: str):
        self.source = source.lower()
        if self.source not in {"mssql", "oracle"}:
            raise ValueError("Unsupported source database. Use 'mssql' or 'oracle'.")

        self._mssql_map: Dict[str, Callable[[List[str]], str]] = {
            "INT": lambda params: "INTEGER",
            "INTEGER": lambda params: "INTEGER",
            "BIGINT": lambda params: "BIGINT",
            "SMALLINT": lambda params: "SMALLINT",
            "TINYINT": lambda params: "SMALLINT",
            "BIT": lambda params: "SMALLINT",
            "FLOAT": _handle_float,
            "REAL": lambda params: "REAL",
            "DECIMAL": lambda params: _with_precision_scale("DECIMAL", params),
            "NUMERIC": lambda params: _with_precision_scale("NUMERIC", params),
            "MONEY": lambda params: "DECIMAL(19, 4)",
            "SMALLMONEY": lambda params: "DECIMAL(10, 4)",
            "DATE": lambda params: "DATE",
            "DATETIME": lambda params: "TIMESTAMP",
            "DATETIME2": lambda params: "TIMESTAMP",
            "SMALLDATETIME": lambda params: "TIMESTAMP",
            "TIME": lambda params: "TIME",
            "CHAR": lambda params: _with_optional_length("CHAR", params),
            "NCHAR": lambda params: _with_optional_length("CHAR", params),
            "VARCHAR": lambda params: _with_optional_length("VARCHAR", params),
            "NVARCHAR": lambda params: _with_optional_length("VARCHAR", params),
            "TEXT": lambda params: "CLOB",
            "NTEXT": lambda params: "CLOB",
            "BINARY": lambda params: _with_optional_length("BINARY", params),
            "VARBINARY": lambda params: _with_optional_length("VARBINARY", params),
            "IMAGE": lambda params: "BLOB",
            "UNIQUEIDENTIFIER": lambda params: "CHAR(36)",
        }

        self._oracle_map: Dict[str, Callable[[List[str]], str]] = {
            "NUMBER": _handle_number,
            "FLOAT": lambda params: "DOUBLE",
            "BINARY_FLOAT": lambda params: "REAL",
            "BINARY_DOUBLE": lambda params: "DOUBLE",
            "DATE": lambda params: "DATE",
            "TIMESTAMP": lambda params: "TIMESTAMP",
            "TIMESTAMP WITH TIME ZONE": lambda params: "TIMESTAMP WITH TIME ZONE",
            "TIMESTAMP WITH LOCAL TIME ZONE": lambda params: "TIMESTAMP WITH TIME ZONE",
            "CHAR": lambda params: _with_optional_length("CHAR", params),
            "NCHAR": lambda params: _with_optional_length("CHAR", params),
            "VARCHAR2": lambda params: _with_optional_length("VARCHAR", params),
            "NVARCHAR2": lambda params: _with_optional_length("VARCHAR", params),
            "CLOB": lambda params: "CLOB",
            "NCLOB": lambda params: "CLOB",
            "BLOB": lambda params: "BLOB",
            "RAW": _handle_raw,
            "LONG RAW": lambda params: "BLOB",
        }

    @staticmethod
    def _parse_type(type_declaration: str) -> Tuple[str, List[str]]:
        cleaned = type_declaration.strip()
        match = re.match(r"([a-zA-Z0-9_ ]+)(?:\((.*)\))?", cleaned)
        if not match:
            return cleaned.upper(), []
        base = _normalize_identifier(match.group(1))
        params_str = match.group(2)
        params = _parse_type_parameters(params_str) if params_str else []
        return base, params

    def _map_type(self, base: str, params: List[str]) -> TypeMappingResult:
        source_map = self._mssql_map if self.source == "mssql" else self._oracle_map
        mapping_func = source_map.get(base)
        if mapping_func:
            try:
                mapped = mapping_func(params)
                return TypeMappingResult(mapped)
            except Exception as exc:  # pragma: no cover - defensive
                return TypeMappingResult(base, f"Failed to convert type {base}({params}): {exc}")
        return TypeMappingResult(base, f"No direct DB2 mapping found for type '{base}'. Using source declaration.")

    def convert(self, type_declaration: str) -> TypeMappingResult:
        base, params = self._parse_type(type_declaration)
        result = self._map_type(base, params)
        if base in {"UNIQUEIDENTIFIER", "IDENTITY", "ROWGUIDCOL"}:
            warning = _identity_warning(type_declaration)
            if result.warning:
                warning = f"{result.warning} {warning}"
            result.warning = warning
        return result


__all__ = ["TypeMapper", "TypeMappingResult"]
